### ISSUE TITLE
[FEATURE] - Define Crafter Machine Recipes

### ISSUE THREAD

**Issue by yoLUkAsss** [PracticaDS/pdes-tp-team_prog#111]
**Is your feature request related to a problem? Please describe.**
I need to know which recipes I can use with the crafter.

**Describe the solution you'd like**
We need to define some recipes like ([Material] -> Material).

**Describe alternatives you've considered**
We can define them in the machine.constants file

**Additional context**
None

**Comment by FedeLochbaum** [comment]
We decided that the implementation of #89  will be separate in two part.
 1 -  First part going to consist in the crafter creation, the idea is show a new tab with the recipes when the machine is selected. Each recipe shall be something like ` 1 x Gold + 2 x Silver = 1 x White Gold `. 
 2 - Second part going to consist in the crafter behavior, check that every recipe material there in his position, if is the case, then produce the new material.
