### ISSUE TITLE
[FEATURE] - Define Furnace Machine Recipes

### ISSUE THREAD

**Issue by yoLUkAsss** [PracticaDS/pdes-tp-team_prog#112]
**Is your feature request related to a problem? Please describe.**
I need to know which recipes I can use with the crafter.

**Describe the solution you'd like**
We need to define some recipes like ([Material] -> Material).

**Describe alternatives you've considered**
We can define them in the machine.constants file

**Additional context**
None

**Comment by FedeLochbaum** [comment]
Maybe could be very similar to the current crafter implementation 🤔 .
