### ISSUE TITLE
[FEATURE] - Define Starter Machine Initial Materials

### ISSUE THREAD

**Issue by yoLUkAsss** [PracticaDS/pdes-tp-team_prog#113]
**Is your feature request related to a problem? Please describe.**
We need to know the materials to select when creating a Starter

**Describe the solution you'd like**
We can define the recipes in the machine constants file

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by FedeLochbaum** [comment]
This should say ` Crafter ` instead `Starter` right ?
