### ISSUE TITLE
[FEATURE] - Define Machine Prices 

### ISSUE THREAD

**Issue by yoLUkAsss** [PracticaDS/pdes-tp-team_prog#114]
**Is your feature request related to a problem? Please describe.**
We need to know the prices of every machine

**Describe the solution you'd like**
We can use the machine constanst file

**Describe alternatives you've considered**
Maybe we shall review this when the backend is being made.

**Additional context**
None

**Comment by FedeLochbaum** [comment]
Makes sense :P currently the `price` values are not following any standard
