### ISSUE TITLE
[FEATURE] - Define How we are going to show the materials inside a Block

### ISSUE THREAD

**Issue by yoLUkAsss** [PracticaDS/pdes-tp-team_prog#115]
**Is your feature request related to a problem? Please describe.**
We need to be able to show the user, the materials being created in the factory grid and how these moves throughout the grid on transporters on melted by the furnace, etc.

**Describe the solution you'd like**
Since there is a possibility where a single block can contain several different materials, perhaps a minimalist approach is more useful and suitable.

**Describe alternatives you've considered**
We may create a new component for showing in a more detailed way all the materials and their quantities.

**Additional context**
We need to have in mind, our grid location on the game, and where is the best possible location for a component like that and how and when it should be rendered.

**Comment by LaimeJesus** [comment]
We've decided that we are going to show a simple coloured ball in a block when there are items.
