### ISSUE TITLE
[FEATURE] - Starter Machine need to select a material to create

### ISSUE THREAD

**Issue by yoLUkAsss** [PracticaDS/pdes-tp-team_prog#116]
**Is your feature request related to a problem? Please describe.**
When selecting a Starter Machine to create on the grid, there should be a list of materials to choose.

**Describe the solution you'd like**
Dropdown?

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by FedeLochbaum** [comment]
I going to use https://material-ui.com/utils/popper/
And.. maybe i could use https://material-ui.com/demos/menus/ for the select options
