### ISSUE TITLE
[FEATURE] - Update the readme

### ISSUE THREAD

**Issue by FedeLochbaum** [PracticaDS/pdes-tp-team_prog#134]
It would be great if we show the travis status, we give any description with the game rules and any gif that shows how the game is :)

**Comment by LaimeJesus** [comment]
Already added, so I'm closing this one
![Screenshot_2019-05-11 PracticaDS pdes-tp-team_prog](https://user-images.githubusercontent.com/13955827/57570488-e3978900-73d8-11e9-80a8-249e04a9bcec.png)
