### ISSUE TITLE
Create Dragable Funcionality: Optional

### ISSUE THREAD

**Issue by LaimeJesus** [PracticaDS/pdes-tp-team_prog#21]
This is a simple drag-able example: [react from scratch draggable](https://github.com/LaimeJesus/react-from-scratch)

**Comment by FedeLochbaum** [comment]
I am thinking if this functionality will be necessary now 🤔 , what do you think @LaimeJesus  ?

**Comment by LaimeJesus** [comment]
It is not necessary at all. I'm closing this one
