### ISSUE TITLE
User can create machines on grid

### ISSUE THREAD

**Issue by yoLUkAsss** [PracticaDS/pdes-tp-team_prog#59]
Si clickeo una celda vacia en la grilla y tengo una maquina seleccionada y tengo el requisito monetario entonces aparece una maquina de ese tipo en la celda seleccionada, decrementando su valor del currency.

**Comment by FedeLochbaum** [comment]
If you have a selected machine type `and` click in an empty cell `and` you have sufficient currency `then` the machine is created in the position selected `and` the currency will be decremented.
