### ISSUE TITLE
Add jest, re-select, -re-compose

### ISSUE THREAD

**Issue by FedeLochbaum** [PracticaDS/pdes-tp-team_prog#6]

**Comment by yoLUkAsss** [comment]
is this necessary? if not, we could just close this for now

**Comment by FedeLochbaum** [comment]
is not necessary but could be fine add at least re-select, with re-select, the selectors use a cache for doesn't the same lookup twice

**Comment by LaimeJesus** [comment]
I'm closing this one if any of you guys want to discuss it again feel free to re open it
