### ISSUE TITLE
Deploy application

### ISSUE THREAD

**Issue by yoLUkAsss** [PracticaDS/pdes-tp-team_prog#65]

**Comment by LaimeJesus** [comment]
We are currently working on trying to deploy the application (auto-magically) using AWS with a student account.  
Should we add that information in this ticket?
This [guide](https://serverless-stack.com/chapters/create-an-s3-bucket.html) looks promising.

**Comment by LaimeJesus** [comment]
We are going to use the gh-pages to do the deploying integrated with github.  

https://reactgo.com/deploy-react-app-github-pages/
