### ISSUE TITLE
Allow move the machine position using move

### ISSUE THREAD

**Issue by FedeLochbaum** [PracticaDS/pdes-tp-team_prog#71]

**Comment by FedeLochbaum** [comment]
This issue depend of #72 . When that ticket be merged, i can start it

**Comment by LaimeJesus** [comment]
I don't understand what do you mean by `move the machine position`.
Do you mean changing the machine input/output direction? for example the starter machine:

![starter-up](https://user-images.githubusercontent.com/13955827/56869966-92ea5e00-69de-11e9-9422-464b42fb2462.png)
![starter-right](https://user-images.githubusercontent.com/13955827/56869965-9251c780-69de-11e9-8e5f-e0c7119e1106.png)
![starter-down](https://user-images.githubusercontent.com/13955827/56869963-9251c780-69de-11e9-9e87-03cb0faebddb.png)
![starter-left](https://user-images.githubusercontent.com/13955827/56869964-9251c780-69de-11e9-907c-8e59390cfcf7.png)

**Comment by FedeLochbaum** [comment]
no, i refer to move a machine to another node, i think that those should be implemented in the rotate action
