### ISSUE TITLE
For each `Tick`, each block should update his production/task/status

### ISSUE THREAD

**Issue by FedeLochbaum** [PracticaDS/pdes-tp-team_prog#77]
Its very possible that the blocks doesn't need do anything.
Investigate if is possible that this taks be implemented by the Grid reducer

**Comment by LaimeJesus** [comment]
What should we do with this issue? @FedeLochbaum.
 
BTW I'm going to create issues for every machine behavior

**Comment by LaimeJesus** [comment]
Closing this one because we are already working on each machine's functionality.
