### ISSUE TITLE
Define Wiki

### ISSUE THREAD

**Issue by FedeLochbaum** [PracticaDS/pdes-tp-team_prog#9]

**Comment by LaimeJesus** [comment]
@yoLUkAsss added a page which says what's the standard that we are using to create issues. 

https://github.com/PracticaDS/pdes-tp-team_prog/wiki/Issue-Creation-Standard

**Comment by LaimeJesus** [comment]
We should prepare a to-do-list with every page and info that we should add on the wiki.
